### ISSUE TITLE
Error: `PY_SSIZE_T_CLEAN macro must be defined for '#' formats`

### ISSUE THREAD

**Issue by bbhtt** [DarwinAwardWinner/rganalysis#14]
```
$ rganalysis -g track Folder/
2023-01-16 22:37:08,538 INFO: Using the audiotools backend to compute ReplayGain info
2023-01-16 22:37:08,543 INFO: Searching for music files in the following locations:
/home/wirt/Music/Folder/
Searching: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "/home/wirt/.local/bin/rganalysis", line 17, in <module>
    plac_call_main()
  File "/home/wirt/.local/bin/rganalysis", line 11, in plac_call_main
    return plac.call(main)
  File "/home/wirt/.local/lib/python3.10/site-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/home/wirt/.local/lib/python3.10/site-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/home/wirt/.local/lib/python3.10/site-packages/rganalysis/main.py", line 148, in main
    track_sets = list(RGTrackSet.MakeTrackSets(tracks, gain_backend=gain_backend))
  File "/home/wirt/.local/lib/python3.10/site-packages/rganalysis/__init__.py", line 334, in MakeTrackSets
    for (dirname, tracks_in_dir) in tracks_by_dir:
  File "/home/wirt/.local/lib/python3.10/site-packages/rganalysis/__init__.py", line 332, in <genexpr>
    tracks = (tr for tr in tracks if gain_backend.supports_file(cast(str, tr.filename)))
  File "/home/wirt/.local/lib/python3.10/site-packages/rganalysis/backends/audiotools.py", line 32, in supports_file
    audiotools.open(fname)
  File "/usr/lib/python3.10/site-packages/audiotools/__init__.py", line 1776, in open
    audio_class = file_type(f)
  File "/usr/lib/python3.10/site-packages/audiotools/__init__.py", line 1740, in file_type
    for b in parse("1p 7u" * 4, False, header[6:10]):
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
Searching: 0it [00:00, ?it/s]
```

With audiotools 3.1.1

**Comment by DarwinAwardWinner** [comment]
From a quick google search, this appears to be an issue with some compiled code in audiotools, not an issue in rganalysis, which has no compiled code. You may need to update or reinstall audiotools, or some other Python package dependency that includes a C extension.
