### ISSUE TITLE
script aborts with error message

### ISSUE THREAD

**Issue by spoo333** [DarwinAwardWinner/rganalysis#15]
When I run rganalysis -m -b audiotools -g auto /[musicdirectory], I get the following error message. What can I do? If I use bs1770gain, I don't get error messages, but no audio file is updated with gain info. Thanks for any help you can provide
(PS on Linux Mint 21.1)

Traceback (most recent call last):
  File "/usr/local/bin/rganalysis", line 17, in <module>
    plac_call_main()
  File "/usr/local/bin/rganalysis", line 11, in plac_call_main
    return plac.call(main)
  File "/usr/local/lib/python3.10/dist-packages/plac_core.py", line 436, in call
    cmd, result = parser.consume(arglist)
  File "/usr/local/lib/python3.10/dist-packages/plac_core.py", line 287, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rganalysis/main.py", line 185, in main
    for ts in tqdm(handled_track_sets, total=iter_len, desc="Analyzing"):
  File "/usr/lib/python3/dist-packages/tqdm/std.py", line 1170, in __iter__
    for obj in iterable:
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 144, in _helper_reraises_exception
    raise ex
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 391, in _guarded_task_generation
    for i, x in enumerate(iterable):
  File "/usr/local/lib/python3.10/dist-packages/rganalysis/__init__.py", line 336, in MakeTrackSets
    for tr in tracks_in_dir:
  File "/usr/local/lib/python3.10/dist-packages/rganalysis/__init__.py", line 332, in <genexpr>
    tracks = (tr for tr in tracks if gain_backend.supports_file(cast(str, tr.filename)))
  File "/usr/local/lib/python3.10/dist-packages/rganalysis/backends/audiotools.py", line 32, in supports_file
    audiotools.open(fname)
  File "/usr/lib/python3/dist-packages/audiotools/__init__.py", line 1776, in open
    audio_class = file_type(f)
  File "/usr/lib/python3/dist-packages/audiotools/__init__.py", line 1740, in file_type
    for b in parse("1p 7u" * 4, False, header[6:10]):
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by DarwinAwardWinner** [comment]
This error comes from compiled code, which means it's not an error in rganalysis and consequently I don't think I can help you. I'm guessing it's an issue with audiotools.

**Comment by spoo333** [comment]
Ok, thanks

**Comment by spoo333** [comment]
PS why do you think does bs177gain not modify audio files when I use it instead of audiotools?

**Comment by DarwinAwardWinner** [comment]
You can try turning on verbose mode and running it again. I'm surprised it's not producing any error messages. Please open a separate issue for that if you still can't solve it.

**Comment by spoo333** [comment]
I ran it with verbose. It doesn't show any error messages ...

**Comment by spoo333** [comment]
2023-02-16 15:57:30,686 INFO: Analysis complete.
2023-02-16 15:57:30,686 DEBUG: Closing transcode process pool

**Comment by spoo333** [comment]
have opened new issue

**Comment by spoo333** [comment]
PS reinstalled Ubuntu 20.4, ran your script with audiotools. No issues whatsoever. You were right. It's audiotools ...
